# src/workflow_16s/downstream/machine_learning/validation/quality_audit.py

import json
import pandas as pd

from pathlib import Path
from typing import Any, List

from workflow_16s.utils.logger import get_logger


class BiomarkerAuditor:
    """
    Automated scientific auditor for 16S Machine Learning results.
    Acts as a 'Certification Gate' for forensic and ecological discovery.
    """
    def __init__(self, output_dir: Path, target: str, level: str = 'Genus'):
        self.base_dir = Path(output_dir)
        self.target = target
        self.level = level
        self.report = []
        self.status = "PASS"

    def _log(self, check_name: str, passed: bool, value: Any, threshold: str):
        status_icon = "✅ PASS" if passed else "❌ FAIL"
        if not passed: 
            self.status = "FAIL"
        self.report.append({
            'Check': check_name,
            'Status': status_icon,
            'Value': str(value),
            'Threshold': threshold
        })

    def run_audit(self) -> bool:
        """Runs the 4-point certification check."""
        logger = get_logger("workflow_16s")
        logger.info(f"🛡️ Certifying Discovery: {self.target} ({self.level})")
        
        # 1. Biological Signal Check
        agnostic_path = self.base_dir / "agnostic" / f"{self.level}_{self.target}" / "results_summary.json"
        if agnostic_path.exists():
            with open(agnostic_path) as f:
                res = json.load(f)
            mcc = res.get('test_scores', {}).get('mcc', 0.0)
            self._log("Biological Signal (MCC)", mcc > 0.40, f"{mcc:.3f}", "> 0.40")
        else:
            self._log("Biological Signal", False, "Missing", "Exists")

        # 2. Generalization Audit (The Gap)
        # Uses the audit results generated by our overfitting_prevention module
        audit_path = self.base_dir / "agnostic" / f"{self.level}_{self.target}" / "overfitting_audit" / "audit_results.json"
        if audit_path.exists():
            with open(audit_path) as f:
                audit = json.load(f)
            gap = audit.get('nested_cv', {}).get('overfitting_gap', 1.0)
            self._log("Overfitting Gap", gap < 0.15, f"{gap:.3f}", "< 0.15")
        else:
            self._log("Overfitting Audit", False, "Missing", "Exists")

        # 3. Statistical Significance Check
        shuffle_path = self.base_dir / "significance_test" / f"{self.level}_{self.target}" / "shuffle_stats.json"
        if shuffle_path.exists():
            with open(shuffle_path) as f:
                sh_res = json.load(f)
            p_val = sh_res.get('p_value', 1.0)
            self._log("Significance (p-val)", p_val < 0.05, f"{p_val:.4f}", "< 0.05")
        
        # 4. Consistency Check (Meta-Analysis)
        meta_path = self.base_dir / "meta_analysis" / "consensus_biomarkers.csv"
        if meta_path.exists():
            df = pd.read_csv(meta_path)
            # Find biomarkers present in > 50% of studies
            stable_count = (df['Frequency_Pct'] >= 0.5).sum()
            self._log("Stable Biomarkers", stable_count >= 3, f"{stable_count}", ">= 3")

        return self.status == "PASS"

    def get_summary_df(self) -> pd.DataFrame:
        return pd.DataFrame(self.report)
    

def verify_run(output_dir: Path, target_names: List[str]) -> bool:
    """
    The main entry point for Tier 4 Certification.
    Scans a completed ML run and generates a 'Pass/Fail' certification log.
    """
    logger = get_logger("workflow_16s")
    logger.info(f"🛡️  Starting Final Certification for: {target_names}")
    
    overall_pass = True
    for target in target_names:
        auditor = BiomarkerAuditor(output_dir, target)
        try:
            auditor.run_audit()
            logger.info(f"✅ Target '{target}' Certification: COMPLETE")
        except Exception as e:
            logger.error(f"❌ Target '{target}' Certification: FAILED - {e}")
            overall_pass = False
            
    return overall_pass