# workflow_16s/upstream/sequences/seqkit.py

import gzip
import io
import json
import os
import shutil
import subprocess
import zipfile
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Dict, List, Any, Tuple, Union, Optional

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from Bio.Seq import Seq
from rich.progress import Progress, BarColumn, TextColumn, TimeElapsedColumn

from workflow_16s.utils.logger import get_logger, with_logger

from .constants import (
    DEFAULT_REGIONS, DEFAULT_PRIMER_REGIONS, DEFAULT_16S_PRIMERS
)

class SeqKitWrapper:
    """A modern wrapper for the SeqKit command-line tool. 
    Provides methods to analyze FASTQ files and summarize statistics.
    
    Attributes:
        max_workers (int): Maximum number of parallel workers to use.
        version (str): Detected version of SeqKit.
    Methods:
        analyze(sample_files: Dict[str, List[Union[str, Path]]]) -> pd.DataFrame: Analyzes the provided FASTQ files and returns a summary DataFrame.
        _process_file(file_path: Path) -> dict: Processes a single FASTQ file and returns its statistics as a dictionary.
    """
    def __init__(self, max_workers: Optional[int] = None):
        self.max_workers = max_workers or os.cpu_count() or 1
        self.version = self._get_version()
        logger = get_logger("workflow_16s")
        logger.info(f"Initialized SeqKitWrapper (using SeqKit v{self.version}).")

    def _get_version(self) -> str:
        stdout, _ = _run_command(["seqkit", "version"], "SeqKit version check")
        return stdout.strip().split()[-1]

    def analyze(self, sample_files: Dict[str, List[Union[str, Path]]]) -> pd.DataFrame:
        flat_files = [(sample, Path(p)) for sample, paths in sample_files.items() for p in paths]
        all_stats = []
        with get_progress_bar() as progress:
            task = progress.add_task("[cyan]Running SeqKit...", total=len(flat_files))
            with ThreadPoolExecutor(max_workers=self.max_workers) as executor:
                futures = {executor.submit(self._process_file, p): (s, p) for s, p in flat_files}
                for future in as_completed(futures):
                    sample_name, _ = futures[future]
                    stats_dict = future.result()
                    stats_dict['sample'] = sample_name
                    all_stats.append(stats_dict)
                    progress.advance(task)
        if not all_stats:
            logger.warning("No statistics were generated by SeqKit.")
            return pd.DataFrame()
        df = pd.DataFrame(all_stats)
        numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
        agg_functions = {col: 'sum' for col in ['num_seqs', 'sum_len', 'sum_gap']}
        agg_functions.update({col: 'min' for col in ['min_len']})
        agg_functions.update({col: 'max' for col in ['max_len']})
        valid_agg_functions = {k: v for k, v in agg_functions.items() if k in df.columns}
        sample_summary = df.groupby('sample').agg(valid_agg_functions).reset_index()
        if 'GC' in numeric_cols and 'sum_len' in sample_summary.columns:
            gc_weighted_avg = df.groupby('sample').apply(lambda x: np.average(x['GC'], weights=x['sum_len'])).reset_index(name='GC')
            sample_summary = pd.merge(sample_summary, gc_weighted_avg, on='sample')
        overall_summary = df.agg(valid_agg_functions)
        overall_summary['sample'] = 'OVERALL'
        if 'GC' in numeric_cols and 'sum_len' in df.columns and df['sum_len'].sum() > 0:
             overall_summary['GC'] = np.average(df['GC'], weights=df['sum_len'])
        final_df = pd.concat([sample_summary, pd.DataFrame([overall_summary])], ignore_index=True)
        if 'sum_len' in final_df.columns and 'num_seqs' in final_df.columns:
            final_df['avg_len'] = (final_df['sum_len'] / final_df['num_seqs'])
        return final_df.round(2)

    def _process_file(self, file_path: Path) -> dict:
        command = ["seqkit", "stats", "-T", "-a", str(file_path)]
        stdout, _ = _run_command(command, f"SeqKit stats for {file_path.name}")
        lines = stdout.strip().split('\n')
        if len(lines) < 2:
            raise ValueError(f"Unexpected output from SeqKit for {file_path.name}: {stdout}")
        headers = [h.replace('.', '').replace('%', '') for h in lines[0].split('\t')]
        values = lines[1].split('\t')
        stats = {}
        for h, v in zip(headers, values):
            try:
                stats[h] = float(v.replace(',', ''))
            except ValueError:
                stats[h] = v
        return stats