# workflow_16s/downstream/meta_analysis.py

"""
Phylogenetic Meta-Analysis of 16S rRNA AnnData Objects
----------------------------------------------------------------------------------------
This script combines multiple AnnData objects (.h5ad files) generated by the
upstream pipeline. It leverages QIIME 2's fragment insertion functionality
to phylogenetically harmonize feature tables from different 16S rRNA subfragments,
allowing for a unified meta-analysis.

Execution requires a QIIME 2 conda environment.

Command-Line Usage:
    conda activate qiime2-shotgun-2024.5  # Or your specific QIIME 2 env
    python -m workflow_16s.downstream.meta_analysis --project_dir /path/to/your/project
"""

# ===================================== IMPORTS ====================================== #

# Standard Library Imports
import argparse
import logging
import sys
from pathlib import Path
from typing import Any, Dict, Tuple, List

# Third-Party Imports
import anndata as ad
import biom
import pandas as pd
import qiime2.plugins as plugins # type: ignore
import qiime2.sdk as sdk # type: ignore
from qiime2 import Artifact # type: ignore

# Local Imports
# Configure sys.path to allow imports from the parent directory (workflow_16s)
# This is necessary for running the script as a module
try:
    from workflow_16s.utils.logger import get_logger
except ImportError:
    # This block allows the script to be run even if the package isn't installed,
    # by adding the parent directory to the Python path.
    script_dir = Path(__file__).parent.parent.absolute()
    if str(script_dir) not in sys.path:
        sys.path.insert(0, str(script_dir))
    from utils.logger import get_logger

# =============================== INITIALIZATION =================================== #

# Initialize logger
logger = get_logger()
logging.basicConfig(level=logging.INFO, 
                    format="[%(asctime)s] %(levelname)-8s %(message)s", 
                    datefmt="%Y-%m-%d %H:%M:%S")

# Load QIIME 2 plugins
try:
    sdk.Context()  # Initialize QIIME 2 SDK
    fragment_insertion = plugins.fragment_insertion.actions
    feature_table_actions = plugins.feature_table.actions
    taxa_actions = plugins.taxa.actions
    logger.info("Successfully loaded QIIME 2 plugins.")
except Exception as e:
    logger.error(f"Failed to load QIIME 2 plugins. Make sure you are in a QIIME 2 Conda environment. Error: {e}")
    sys.exit(1)

# ============================= CORE FUNCTIONS =================================== #

def load_qiime2_references(ref_dir: Path) -> Tuple[Artifact, Artifact]:
    """
    Loads the Greengenes2 reference phylogeny and taxonomy artifacts.
    
    Args:
        ref_dir: Directory containing the reference .qza files.

    Returns:
        A tuple containing the phylogeny and taxonomy artifacts.
    """
    gg2_phylogeny_path = ref_dir / "gg-2022-10-ssu-nr99-full-length-phylogeny.qza"
    gg2_taxonomy_path = ref_dir / "gg-2022-10-ssu-nr99-taxonomy.qza"

    if not gg2_phylogeny_path.exists() or not gg2_taxonomy_path.exists():
        logger.error(f"Greengenes2 reference files not found in '{ref_dir}'.")
        logger.info("Please download them from https://data.qiime2.org/2022.10/common/")
        sys.exit(1)

    logger.info("Loading Greengenes2 reference artifacts...")
    phylogeny = Artifact.load(str(gg2_phylogeny_path))
    taxonomy = Artifact.load(str(gg2_taxonomy_path))
    return phylogeny, taxonomy

def anndata_to_qiime2_artifacts(adata: ad.AnnData) -> Tuple[Artifact, Artifact]:
    """
    Converts data from an AnnData object into QIIME 2 Artifacts.

    Args:
        adata: The AnnData object to convert.

    Returns:
        A tuple of (FeatureTable[Frequency], FeatureData[Sequence]) artifacts.
    """
    subset_id = adata.uns.get('subset_id', 'unknown_subset')
    logger.info(f"Converting AnnData object '{subset_id}' to QIIME 2 artifacts.")

    # 1. Create BIOM table from adata.X (counts)
    # AnnData is (samples x features), BIOM/QIIME2 is (features x samples), so we transpose.
    X = adata.X
    # Convert to dense numpy array if necessary
    import numpy as np
    try:
        from scipy import sparse
        is_sparse = sparse.issparse(X)
    except ImportError:
        is_sparse = False

    if is_sparse:
        X_dense = X.A if hasattr(X, "A") else X.todense()
    else:
        # Handles numpy arrays, masked arrays, h5py arrays, etc.
        X_dense = np.asarray(X)
    counts_df = pd.DataFrame(X_dense.T, index=adata.var_names, columns=adata.obs_names)
    biom_table = biom.Table(counts_df.values, observation_ids=counts_df.index, sample_ids=counts_df.columns)
    table_artifact = Artifact.import_data("FeatureTable[Frequency]", biom_table)

    # 2. Create sequences series from adata.var
    # We assume representative sequences are stored in .var['sequence'] or .uns['rep_seqs']
    if 'sequence' in adata.var.columns:
        sequences_series = adata.var['sequence']
    elif 'rep_seqs' in adata.uns and isinstance(adata.uns['rep_seqs'], dict):
        # Ensure the sequence series is aligned with the feature table columns (adata.var_names)
        sequences_series = pd.Series(adata.uns['rep_seqs']).reindex(adata.var_names)
    else:
        raise ValueError(f"Representative sequences not found in AnnData object for '{subset_id}'. "
                         "Expected in `adata.var['sequence']` or `adata.uns['rep_seqs']`.")
    
    # Drop features with no sequence data
    sequences_series.dropna(inplace=True)
    
    seq_artifact = Artifact.import_data("FeatureData[Sequence]", sequences_series)

    return table_artifact, seq_artifact

def run_meta_analysis(project_dir: Path, ref_dir: Path):
    """
    Main function to run the phylogenetic meta-analysis pipeline.
    
    Args:
        project_dir: The root directory of the project.
        ref_dir: Directory containing QIIME 2 reference artifacts.
    """
    processed_data_dir = project_dir / "processed_data"
    output_dir = project_dir / "downstream_analysis"
    output_dir.mkdir(exist_ok=True)
    
    h5ad_files = list(processed_data_dir.glob("*.h5ad"))
    if not h5ad_files:
        logger.error(f"No .h5ad files found in '{processed_data_dir}'. Halting analysis.")
        return

    logger.info(f"Found {len(h5ad_files)} AnnData files to process.")
    
    gg2_phylogeny, gg2_taxonomy = load_qiime2_references(ref_dir)

    collapsed_tables = []
    all_metadata_dfs = []

    for h5ad_path in h5ad_files:
        try:
            logger.info(f"--- Processing: {h5ad_path.name} ---")
            adata = ad.read_h5ad(h5ad_path)
            
            # Skip if anndata is empty
            if adata.n_obs == 0 or adata.n_vars == 0:
                logger.warning(f"Skipping empty AnnData object: {h5ad_path.name}")
                continue

            # Step 1: Convert AnnData to QIIME 2 Artifacts
            table_qza, rep_seqs_qza = anndata_to_qiime2_artifacts(adata)

            # Step 2: Phylogenetic Placement with SEPP
            logger.info(f"Running phylogenetic placement (SEPP) for {adata.uns['subset_id']}...")
            placement_results = fragment_insertion.sepp(
                representative_sequences=rep_seqs_qza,
                reference_database=gg2_phylogeny,
                threads=4  # Adjust as needed
            )

            # Step 3: Collapse Feature Table to Species Level (Level 7)
            logger.info(f"Collapsing feature table for {adata.uns['subset_id']}...")
            collapsed_table_result = taxa_actions.collapse(
                table=table_qza,
                taxonomy=gg2_taxonomy,
                level=7  # Species level
            )
            collapsed_tables.append(collapsed_table_result.collapsed_table)

            # Collect metadata
            all_metadata_dfs.append(adata.obs)

        except Exception as e:
            logger.error(f"Failed to process {h5ad_path.name}. Error: {e}", exc_info=True)
            
    if not collapsed_tables:
        logger.error("No tables were successfully processed. Cannot proceed with merging.")
        return

    # Step 4: Merge Collapsed Feature Tables
    logger.info(f"Merging {len(collapsed_tables)} processed feature tables...")
    merged_table_result = feature_table_actions.merge(
        tables=collapsed_tables,
        overlap_method='sum'
    )
    merged_table_qza = merged_table_result.merged_table

    # Step 5: Combine Metadata
    logger.info("Combining metadata from all datasets...")
    combined_metadata_df = pd.concat(all_metadata_dfs, axis=0, join='outer', sort=False)
    # Ensure sample IDs are unique
    if combined_metadata_df.index.duplicated().any():
        logger.warning("Duplicate sample IDs found in metadata. Consider namespacing them if they originate from different datasets but share IDs.")

    # Step 6: Create Final Merged AnnData Object
    logger.info("Creating final merged AnnData object...")
    merged_counts_df = merged_table_qza.view(pd.DataFrame) # This is features x samples
    
    # Align metadata and feature table
    final_metadata = combined_metadata_df.reindex(merged_counts_df.columns)
    
    # Create the final AnnData object (transpose counts to be samples x features)
    final_adata = ad.AnnData(X=merged_counts_df.T, obs=final_metadata)
    final_adata.uns['phylogenetic_reference'] = 'Greengenes2 2022.10'
    
    # Save the final object
    final_output_path = output_dir / "meta_analysis_merged.h5ad"
    logger.info(f"Saving final merged AnnData object to: {final_output_path}")
    final_adata.write(final_output_path, compression="gzip")
    
    logger.info("--- Meta-analysis complete! ---")

# ================================== MAIN EXECUTION ================================== #

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Run phylogenetic meta-analysis on 16S data.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        "--project_dir",
        type=Path,
        required=True,
        help="The root directory of your 16S workflow project.\n"
             "This script expects to find a 'processed_data' subdirectory with .h5ad files here."
    )
    parser.add_argument(
        "--ref_dir",
        type=Path,
        default=Path.home() / ".qiime2/references",
        help="Directory containing the Greengenes2 reference files.\n"
             "Default: ~/.qiime2/references/"
    )
    args = parser.parse_args()

    # Create reference directory if it doesn't exist
    args.ref_dir.mkdir(parents=True, exist_ok=True)
    
    run_meta_analysis(project_dir=args.project_dir, ref_dir=args.ref_dir)